server:
  port: 8004
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: springcloud-Config8004   #\u914D\u7F6E\u670D\u52A1\u5B9E\u4F8B\u663E\u793A\u540D\u79F0
    prefer-ip-address: true     #\u670D\u52A1\u5B9E\u4F8Bip\u5730\u5740
      
      
spring:
  application:
    name: springcloud-configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/menglingchong/springcloudconfig-repo.git
          username: 282733193@qq.com
          password: github2015
          basedir: E:/JavaPrograms/JavaWeb/springcloudDemo/SpringcloudDemo/springcloud_sell/config/basedir
#          search-paths:  #\u914D\u7F6E\u4ED3\u5E93\u8DEF\u5F84\u4E0B\u7684\u76F8\u5BF9\u641C\u7D22\u4F4D\u7F6E\uFF0C\u53EF\u4EE5\u914D\u7F6E\u591A\u4E2A
  rabbitmq:
#    host: 10.126.2.179
    host: 192.168.1.7
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    
#将springcloudBus的接口暴露出去，否则更新refresh不起作用
management:
  endpoints:
    web:
      exposure:  # expose: "*" 已过期
        include: "*"
  endpoint:
    bus-refresh:
      enabled: true