server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway

#\u8DEF\u7531\u8BBF\u95EE\u6620\u5C04\u89C4\u5219
zuul:
  prefix: /atguigu #\u6DFB\u52A0\u8DEF\u7531\u7684\u516C\u5171\u524D\u7F00
  ignored-services: microservicecloud-dept  #\u539F\u771F\u5B9E\u7684\u670D\u52A1\u540D\u5FFD\u7565
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
  


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com  #\u81EA\u5B9A\u4E49\u5FAE\u670D\u52A1\u5B9E\u4F8B\u540D\uFF0C\u53EF\u4FEE\u6539hosts, myzuul.com\u6620\u5C04\u5230127.0.0.1 
    prefer-ip-address: true


info:
  app.name: atguigu-microcloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

